Setup CI
eosnetworkfoundation/silkworm pull request #106
Opened 2023-12-05 16:39 UTC by yarkinwho

And fix some tests.

2023-12-07 19:27 UTC, arhag requested changes

2023-12-07 19:27 UTC, arhag commented on .github/workflows/build-node.sh
> +#!/bin/bash
Rename file to `build-tests.sh`.

2023-12-07 19:27 UTC, arhag commented on .github/workflows/node.md
> +# EOS EVM Silkworm CI
Rename the file to `silkworm.md`.

2023-12-07 19:27 UTC, arhag commented on .github/workflows/node.yml
> +name: EOS EVM Silkworm CI
Rename the file to `silkworm.yml`.

2023-12-08 03:05 UTC, elmato approved these changes

2023-12-08 05:33 UTC, yarkinwho commented on .github/workflows/node.md
> +# EOS EVM Silkworm CI
done

2023-12-08 05:33 UTC, yarkinwho commented on .github/workflows/node.yml
> +name: EOS EVM Silkworm CI
done

2023-12-13 01:55 UTC, arhag approved these changes

2023-12-14 01:42 UTC, merged